const CONFIG = {
    introTitle: 'Sannn à!',
    introDesc: `Anh sắp chuyển nhà rồi… Chuyển hộ khẩu vào trái tim em!`,
    btnIntro: 'hi babi',
    title: '2. Bầu trời xanh, làn mây trắng. Em yêu nắng hay yêu Anh? 😙',
    desc: '#dangphamnguyetsan ',
    btnYes: 'Là anh đó <33',
    btnNo: 'Nắng nhaaa :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Vì anh deptrai vlllll <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay chơi game nhé công chúa<3.',
    btnAccept: 'Okiiiii lun <3',
}
