const CONFIG = {
    introTitle: 'Sannn à!',
    introDesc: `Anh sắp chuyển nhà rồi… Chuyển hộ khẩu vào trái tim em!`,
    btnIntro: 'Hi Bae:3',
    title: 'Bầu trời xanh, làn mây trắng. Em yêu nắng hay yêu anh? 😙',
    desc: '#dangphamnguyetsang ',
    btnYes: 'Yêu anh đó <33',
    btnNo: 'Nắng nhaaa :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Vì anh deptrai vllll <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay chơi game nhé công chúa.',
    btnAccept: 'Okiiiii lun <3',
}
